### ISSUE TITLE
does reflect-metadata work

### ISSUE THREAD

**Issue by ovesco** [garronej/denoify#4]
Hey nice project!
Just tried to use it with one of my own: https://github.com/ovesco/diosaur
But it fails miserably with the following error:
```
C:\Users\Guillaume Hochet\Desktop\jshare\ddi\node_modules\denoify\bin\denoify.js:6
process.once("unhandledRejection", error => { throw error; });
                                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:113:11)
    at Object.relative (path.js:438:5)
    at Object.isInsideOrIsDir (C:\Users\Guillaume Hochet\Desktop\jshare\ddi\node_modules\denoify\tools\isInsideOrIsDir.js:7:27)
    at Object.denoify (C:\Users\Guillaume Hochet\Desktop\jshare\ddi\node_modules\denoify\lib\denoify.js:29:28)
    at Object.<anonymous> (C:\Users\Guillaume Hochet\Desktop\jshare\ddi\node_modules\denoify\bin\denoify.js:15:11)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I believe it might be related to the use of `reflect-metadata` but didn't find any note about this in the readme, is it supported? Asking because I'm not sure if I should consider it a package to denoify before

Thanks!

**Comment by garronej** [comment]
Hey, 
Hold on let me have a look :octocat:

**Comment by garronej** [comment]
@ovesco Sorry the error message is not very meaningful I have to improve that.  
Denoify needs a ``main`` field in the ``package.json``.
Check out my PR for diosaur, everything should be working, come back to me if it is not the case.

Keep up the good work 👍

**Comment by ovesco** [comment]
Oh my bad quite ashamed then ahah, Thanks for the help ! You might also want to add a special note about reflection in denoify to say it is supported if the library depends on it :)

**Comment by garronej** [comment]
Thank you for the kind words,

Regarding ``reflect-metadata``, it is not supported out of the box,  I had to add a ``denoPorts`` entry in your package.json, I won't add it in the know-port.json yet because it does not import the types definitions so it forces you to use ts-ignore. I have to investigate how to get the port supported with https://github.com/denoland/deno/pull/2746
I will tell you when I sorted that out.

**Comment by garronej** [comment]
Until then I re-open the issue

**Comment by garronej** [comment]
For future reference: https://github.com/ovesco/diosaur/pull/4
