### ISSUE TITLE
Increase node fetch timeout

### ISSUE THREAD

**Issue by garronej** [garronej/denoify#58]
In Vietnam (slow to resolve links hosted in the US or Europe) I had many of theses:  

```raw
 ✗ joseph @ MacBook-Pro ~/github/tsafe $ yarn build
yarn run v1.22.19
$ tsc && denoify
Denoify is reading sources files from src
Deno distribution will be generated at deno_dist

/Users/joseph/github/tsafe/node_modules/denoify/bin/denoify.js:7
    throw error;
    ^
FetchError: network timeout at: https://deno.land/std@0.152.0/node/fs.ts
    at Timeout.<anonymous> (/Users/joseph/github/tsafe/node_modules/node-fetch/lib/index.js:1484:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  type: 'request-timeout'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by garronej** [comment]
I still get problem with deno.land/x url timeout... 

According to gpt there's no default timeout so it might not be the root cause of the issue.  
Maybe the server is just not responding.  
https://chat.openai.com/share/8b2518ab-c475-42f7-ad1d-a3dc76ff729b
